/*
 * This file is generated by jOOQ.
 */
package ch.niculin.contactdairy.jooq;


import ch.niculin.contactdairy.jooq.tables.Datum;
import ch.niculin.contactdairy.jooq.tables.Kontakt;
import ch.niculin.contactdairy.jooq.tables.Person;
import ch.niculin.contactdairy.jooq.tables.SqliteSequence;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>Datum</code>.
     */
    public final Datum DATUM = Datum.DATUM;

    /**
     * The table <code>Kontakt</code>.
     */
    public final Kontakt KONTAKT = Kontakt.KONTAKT;

    /**
     * The table <code>Person</code>.
     */
    public final Person PERSON = Person.PERSON;

    /**
     * The table <code>sqlite_sequence</code>.
     */
    public final SqliteSequence SQLITE_SEQUENCE = SqliteSequence.SQLITE_SEQUENCE;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Datum.DATUM,
            Kontakt.KONTAKT,
            Person.PERSON,
            SqliteSequence.SQLITE_SEQUENCE
        );
    }
}
