/*
 * This file is generated by jOOQ.
 */
package ch.niculin.contactdairy.jooq;


import ch.niculin.contactdairy.jooq.tables.Datum;
import ch.niculin.contactdairy.jooq.tables.Kontakt;
import ch.niculin.contactdairy.jooq.tables.Person;
import ch.niculin.contactdairy.jooq.tables.SqliteSequence;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>Datum</code>.
     */
    public static final Datum DATUM = Datum.DATUM;

    /**
     * The table <code>Kontakt</code>.
     */
    public static final Kontakt KONTAKT = Kontakt.KONTAKT;

    /**
     * The table <code>Person</code>.
     */
    public static final Person PERSON = Person.PERSON;

    /**
     * The table <code>sqlite_sequence</code>.
     */
    public static final SqliteSequence SQLITE_SEQUENCE = SqliteSequence.SQLITE_SEQUENCE;
}
